apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

images:
  # - name: us.gcr.io/smart-city-unal/smart-city-unal
  - name: nano2766/smart-city-unal
    # Image is appended based on package.json version
    newTag: 1.5.9
