@startuml
actor User as ApplicationUser
participant APIGateway
participant SensorsMicroservice
participant IngestionMicroservice
participant MessageBroker
database Database
participant EdgeGateway
queue MQTTBroker
participant PhysicalDevice

ApplicationUser -> APIGateway: Query Data (SensorId)
APIGateway -> IngestionMicroservice: Query Data (SensorId)
activate IngestionMicroservice
IngestionMicroservice -> Database: Get Sensor Data (SensorId)
Database --> IngestionMicroservice: Return Sensor Data
IngestionMicroservice --> APIGateway: Return Sensor Data
deactivate IngestionMicroservice
APIGateway --> ApplicationUser: Return Sensor Data

PhysicalDevice -> MQTTBroker: Publish Device Data Topic
EdgeGateway -> MQTTBroker: Subscribe Device Data Topic
EdgeGateway -> IngestionMicroservice: Publish Device Data Via HTTPS
activate IngestionMicroservice
IngestionMicroservice -> MessageBroker: Find Sensor Metadata
activate SensorsMicroservice
MessageBroker -> SensorsMicroservice: Find Sensor Metadata
SensorsMicroservice -> Database: Get Sensor Metadata
Database -> SensorsMicroservice: Returns Sensor Metadata
SensorsMicroservice -> MessageBroker:  Returns Sensor Metadata
MessageBroker -> IngestionMicroservice:  Returns sensor Metadata
IngestionMicroservice -> Database: Insert sensor Data in DB
deactivate IngestionMicroservice
deactivate SensorsMicroservice
@enduml
